export const GROUP_LIST_REFRESH_EVENT = "GROUP_LIST_REFRESH";
export const ACCOUNT_LIST_REFRESH_EVENT = "ACCOUNT_LIST_REFRESH";
export const TRANSACTION_LIST_REFRESH_EVENT = "TRANSACTION_LIST_REFRESH";
export const BANK_TRANSACTION_LIST_REFRESH_EVENT = "BANK_TRANSACTION_LIST_REFRESH";
export const USER_LIST_REFRESH_EVENT = "USER_LIST_REFRESH";