version: 0.0
os: linux
files:
  - source: /*
    # destination: /usr/share/nginx/html/
    destination: /home/ec2-user/accounts/test-code-deploy/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    # - location: scripts/install_dependencies
    #   timeout: 300
    #   runas: root
    # - location: scripts/start_server
    #   timeout: 300
    #   runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root